version: '3.8'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  plenna-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plenna-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - mongodb

volumes:
  mongo_data:
    driver: local
